spring:
  application:
    name: defense
url:
 entorno:
  threats: 'https://proyecto-final-entorno.onrender.com/threats'
 comm:
  message: 'https://proyecto-final-entorno.onrender.com/threats'
monitor:
  minutes: 5m
